-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.featureclass
(
    fid smallint NOT NULL,
    fclass text COLLATE pg_catalog."default",
    CONSTRAINT featureclass_pkey PRIMARY KEY (fid)
);

CREATE TABLE IF NOT EXISTS public.ref
(
    rid bigint NOT NULL DEFAULT nextval('ref_id'::regclass),
    ref text COLLATE pg_catalog."default",
    CONSTRAINT ref_pkey PRIMARY KEY (rid)
);

CREATE TABLE IF NOT EXISTS public.refmany
(
    road_id integer NOT NULL,
    ref_id bigint NOT NULL,
    CONSTRAINT refmany_pkey PRIMARY KEY (road_id, ref_id)
);

CREATE TABLE IF NOT EXISTS public.roadname
(
    nid integer,
    name text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.roads
(
    id integer NOT NULL,
    osm_id bigint NOT NULL,
    code smallint NOT NULL,
    oneway character varying(1) COLLATE pg_catalog."default" NOT NULL,
    maxspeed smallint NOT NULL,
    layer smallint NOT NULL,
    bridge boolean NOT NULL,
    tunnel boolean NOT NULL,
    geom geometry NOT NULL,
    CONSTRAINT roads_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.refmany
    ADD CONSTRAINT refmany_ref_id_fkey FOREIGN KEY (ref_id)
    REFERENCES public.ref (rid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.refmany
    ADD CONSTRAINT refmany_road_id_fkey FOREIGN KEY (road_id)
    REFERENCES public.roads (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.roadname
    ADD CONSTRAINT roadname_nid_fkey FOREIGN KEY (nid)
    REFERENCES public.roads (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.roads
    ADD CONSTRAINT roads_code_fkey FOREIGN KEY (code)
    REFERENCES public.featureclass (fid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;